### PR TITLE
Rename variables related to registry

### PR DESCRIPTION
**Pull request by vanGastelJS**
Per suggestion of #34 , renamed variables related to docker image registry.

Renamed variables: 

- DOCKER_USERNAME => REGISTRY_USERNAME
- DOCKER_PASSWORD => REGISTRY_TOKEN
- DOCKER_REGISTRY => REGISTRY_URL

Also derived internal variable names are renamed according to the renaming above.

Also update LICENSE.md to extend copyright to include current year

### CODE REVIEW

**Comment by Brend-Smits** [comment]
Thank you for contributing @vanGastelJS, this looks great!

This is quite a severe breaking change. For this reason, I would like to wait for the main maintainer @JeroenKnoops. 
This would get an approval from my end.

**Comment by JeroenKnoops** [comment]
Looks good. We have to make sure it's clear in the release notes as this is breaking change.
Time of a new major version!

**Comment by JeroenKnoops** [comment]
I will add a version in between with a deprecation warning..

**Comment by JeroenKnoops** [comment]
Testing the release in: https://github.com/philips-software/docker-node/actions/runs/2963311948

**Pull request closed without merging**
